// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package gobpfs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	NetworkMonitorMapEvents          = "events"
	NetworkMonitorProgTpTcpSendReset = "tp_tcp_send_reset"
)

// LoadNetworkMonitor returns the embedded CollectionSpec for NetworkMonitor.
func LoadNetworkMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetworkMonitor: %w", err)
	}

	return spec, err
}

// LoadNetworkMonitorObjects loads NetworkMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetworkMonitorObjects
//	*NetworkMonitorPrograms
//	*NetworkMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetworkMonitorObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetworkMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetworkMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkMonitorSpecs struct {
	NetworkMonitorProgramSpecs
	NetworkMonitorMapSpecs
	NetworkMonitorVariableSpecs
}

// NetworkMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkMonitorProgramSpecs struct {
	TpTcpSendReset *ebpf.ProgramSpec `ebpf:"tp_tcp_send_reset"`
}

// NetworkMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkMonitorMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// NetworkMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkMonitorVariableSpecs struct {
}

// NetworkMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkMonitorObjects struct {
	NetworkMonitorPrograms
	NetworkMonitorMaps
	NetworkMonitorVariables
}

func (o *NetworkMonitorObjects) Close() error {
	return _NetworkMonitorClose(
		&o.NetworkMonitorPrograms,
		&o.NetworkMonitorMaps,
	)
}

// NetworkMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkMonitorMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *NetworkMonitorMaps) Close() error {
	return _NetworkMonitorClose(
		m.Events,
	)
}

// NetworkMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkMonitorVariables struct {
}

// NetworkMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkMonitorPrograms struct {
	TpTcpSendReset *ebpf.Program `ebpf:"tp_tcp_send_reset"`
}

func (p *NetworkMonitorPrograms) Close() error {
	return _NetworkMonitorClose(
		p.TpTcpSendReset,
	)
}

func _NetworkMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed networkmonitor_bpfeb.o
var _NetworkMonitorBytes []byte
