// Code generated by MockGen. DO NOT EDIT.
// Source: firewall.go
//
// Generated by this command:
//
//	mockgen -source=firewall.go -destination=mocks/firewall_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFirewall is a mock of Firewall interface.
type MockFirewall struct {
	ctrl     *gomock.Controller
	recorder *MockFirewallMockRecorder
	isgomock struct{}
}

// MockFirewallMockRecorder is the mock recorder for MockFirewall.
type MockFirewallMockRecorder struct {
	mock *MockFirewall
}

// NewMockFirewall creates a new mock instance.
func NewMockFirewall(ctrl *gomock.Controller) *MockFirewall {
	mock := &MockFirewall{ctrl: ctrl}
	mock.recorder = &MockFirewallMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirewall) EXPECT() *MockFirewallMockRecorder {
	return m.recorder
}

// Ban mocks base method.
func (m *MockFirewall) Ban(ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ban", ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ban indicates an expected call of Ban.
func (mr *MockFirewallMockRecorder) Ban(ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ban", reflect.TypeOf((*MockFirewall)(nil).Ban), ip)
}

// Unban mocks base method.
func (m *MockFirewall) Unban(ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unban", ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unban indicates an expected call of Unban.
func (mr *MockFirewallMockRecorder) Unban(ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unban", reflect.TypeOf((*MockFirewall)(nil).Unban), ip)
}
