// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBanPool is a mock of BanPool interface.
type MockBanPool struct {
	ctrl     *gomock.Controller
	recorder *MockBanPoolMockRecorder
	isgomock struct{}
}

// MockBanPoolMockRecorder is the mock recorder for MockBanPool.
type MockBanPoolMockRecorder struct {
	mock *MockBanPool
}

// NewMockBanPool creates a new mock instance.
func NewMockBanPool(ctrl *gomock.Controller) *MockBanPool {
	mock := &MockBanPool{ctrl: ctrl}
	mock.recorder = &MockBanPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBanPool) EXPECT() *MockBanPoolMockRecorder {
	return m.recorder
}

// BanIP mocks base method.
func (m *MockBanPool) BanIP(ctx context.Context, ip string, banSeconds uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BanIP", ctx, ip, banSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// BanIP indicates an expected call of BanIP.
func (mr *MockBanPoolMockRecorder) BanIP(ctx, ip, banSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BanIP", reflect.TypeOf((*MockBanPool)(nil).BanIP), ctx, ip, banSeconds)
}

// RestoreBans mocks base method.
func (m *MockBanPool) RestoreBans(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreBans", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreBans indicates an expected call of RestoreBans.
func (mr *MockBanPoolMockRecorder) RestoreBans(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreBans", reflect.TypeOf((*MockBanPool)(nil).RestoreBans), ctx)
}

// UnbanIP mocks base method.
func (m *MockBanPool) UnbanIP(ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnbanIP", ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnbanIP indicates an expected call of UnbanIP.
func (mr *MockBanPoolMockRecorder) UnbanIP(ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnbanIP", reflect.TypeOf((*MockBanPool)(nil).UnbanIP), ip)
}
