// Code generated by MockGen. DO NOT EDIT.
// Source: monitor.go
//
// Generated by this command:
//
//	mockgen -source=monitor.go -destination=mocks/monitor_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	config "open-defender/pkg/config"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMonitorHub is a mock of MonitorHub interface.
type MockMonitorHub struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorHubMockRecorder
	isgomock struct{}
}

// MockMonitorHubMockRecorder is the mock recorder for MockMonitorHub.
type MockMonitorHubMockRecorder struct {
	mock *MockMonitorHub
}

// NewMockMonitorHub creates a new mock instance.
func NewMockMonitorHub(ctrl *gomock.Controller) *MockMonitorHub {
	mock := &MockMonitorHub{ctrl: ctrl}
	mock.recorder = &MockMonitorHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitorHub) EXPECT() *MockMonitorHubMockRecorder {
	return m.recorder
}

// RunBaseMonitor mocks base method.
func (m *MockMonitorHub) RunBaseMonitor(name string, bm *config.BaseFields) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunBaseMonitor", name, bm)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunBaseMonitor indicates an expected call of RunBaseMonitor.
func (mr *MockMonitorHubMockRecorder) RunBaseMonitor(name, bm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunBaseMonitor", reflect.TypeOf((*MockMonitorHub)(nil).RunBaseMonitor), name, bm)
}

// RunMonitoring mocks base method.
func (m *MockMonitorHub) RunMonitoring() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RunMonitoring")
}

// RunMonitoring indicates an expected call of RunMonitoring.
func (mr *MockMonitorHubMockRecorder) RunMonitoring() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunMonitoring", reflect.TypeOf((*MockMonitorHub)(nil).RunMonitoring))
}

// RunResourceMonitor mocks base method.
func (m *MockMonitorHub) RunResourceMonitor(rm *config.ResourceMonitorConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunResourceMonitor", rm)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunResourceMonitor indicates an expected call of RunResourceMonitor.
func (mr *MockMonitorHubMockRecorder) RunResourceMonitor(rm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunResourceMonitor", reflect.TypeOf((*MockMonitorHub)(nil).RunResourceMonitor), rm)
}
